### PR TITLE
Add jammy support

### PR DESCRIPTION
**Pull request by axldd**

### CODE REVIEW

**Comment by andrekeller** [comment]
I'd probably just remove the special handling for the 16.04 systems and release this as a version 2.0

**Comment by axldd** [comment]
Removed Ubuntu 16.04 support and changed version to 2.0.0

**Comment by andrekeller** [comment]
If we don't need to support 16.04 you can remove the whole release specific logic

**Comment by andrekeller** [comment]
(i.e. remove all the defaults_file handling, also in config.pp)

**Comment by axldd** [comment]
Oversaw that, will fix

**Comment by andrekeller** [comment]
lgtm

**Pull request merged**
